# Generated by Django 5.2 on 2025-10-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
