# Generated by Django 5.2 on 2025-10-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalarticle',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
